@extends('fronthead')

@section('title', 'Privacy')

@section('content')

<div id="intro" class="jarallax" data-speed="0.5" style="background-image: url(img/intro_img/1.jpg);">
      <div class="grid grid--container">
        <div class="row row--xs-middle">
          <div class="col col--lg-5 text--center">
            <h1 class="__title">Privacy Policy</h1>
            
          </div>
        </div>
      </div>
    </div>
    <!-- end intro -->
<main role="main">

    <section class="section section--no-pb">
        <div class="grid grid--container">
          <div class="content-container">

<h4>Cryptvault Privacy Policy</h4>
<p>Effective date: January 31, 2017</p>

<p>Your privacy is important to Cryptvault. So we’ve developed a Privacy Policy that covers how we collect, use, disclose, transfer, and store your information. Please take a moment to familiarize yourself with our privacy practices and contact us if you have any questions. Thanks for entrusting Cryptvault with your source code, your projects, and your personal information. Holding onto your private information is a serious responsibility, and we want you to know how we’re handling it.</p>

<p><strong>The short version</strong></p>
<p>We collect your information only with your consent; we only collect the minimum amount of personal information that is necessary to fulfill the purpose of your interaction with us; we don’t sell it to third parties; and we only use it as this Privacy Statement describes. If you’re visiting us from the US: we comply with the Federal Trade Commission (FTC) as well as IRS.</p>

<p>Of course, the short version doesn’t tell you everything, so please read on for more details!</p>

<p><strong>What information Cryptvault collects and why</strong></p>
<p><strong>Information from website browsers</strong></p>
<p>If you’re just browsing the website, we collect the same basic information that most websites collect. We use common internet technologies, such as cookies and web server logs. This is stuff we collect from everybody, whether they have an account or not. The information we collect about all visitors to our website includes the visitor’s browser type, language preference, referring site, additional websites requested, and the date and time of each visitor request. We also collect potentially personally-identifying information like Internet Protocol (IP) addresses. Why do we collect this?</p>

<p>We collect this information to better understand how our website visitors use Cryptvault and to monitor and protect the security of the website. Information from users with accounts.</p>

<p>If you create an account, we require some basic information at the time of account creation. You will create your own user name and password, and we will ask you for a valid email account. You also have the option to give us more information if you want to, and this may include “User Personal Information.” “User Personal Information” is any information about one of our users which could, alone or together with other information, personally identify him or her. Information such as a user name and password, an email address and a real name are examples of “User Personal Information.” User Personal Information does not include aggregated, non-personally identifying information. We may use aggregated, non-personally identifying information to operate, improve, and optimize our website and service. Why do we collect this?
</p>
<p>* We need your User Personal Information to create your account, and to provide the services you request.</p>
<p>* We use your User Personal Information, specifically your user name, to identify you on the Cryptvault server.</p>
<p>* We use it to fill out your profile and share that profile with other users if you ask us to.</p>
<p> We will use your email address to communicate with you, if you’ve said that’s okay, and only for the reasons you’ve said that’s okay. Please see our section on email communication for more information.</p>*
<p>* We limit our use of your User Personal Information to the purposes listed in this Privacy Statement. If we need to use your User Personal Information for other purposes, we will ask your permission first. You can always see what information we have, how we’re using it, and what permissions you have given us in your user profile.</p>
<p>What information Cryptvault does not collect We do not intentionally collect sensitive personal information, such as social security numbers, genetic data, health information, or religious information. Although Cryptvault does not request or intentionally collect any sensitive personal information, we realize that you might store this kind of information in your account, such as in a repository. If you store any sensitive personal information on our servers, you are consenting to our storage of that information on our servers, which are is in the UK. We do not intentionally collect information that is stored in your repositories or other free-form content inputs. Information in your repositories belongs to you, and you are responsible for it, as well as for making sure that your content complies with our Terms of Service. Cryptvault employees do not access private repositories unless required to for security or maintenance, or for support reasons, with the consent of the repository owner. If your repository is public, anyone (including us) may view its contents. If you have included private or sensitive information in your public repository, such as email addresses, that information may be indexed by search engines or used by third parties. In addition, while we do not generally search for content in your repositories, we may scan our servers for certain tokens or security signatures. If you’re a child under the age of 13, you may not have an account on Cryptvault. Cryptvault does not knowingly collect information from or direct any of our content specifically to children under 13. If we learn or have reason to suspect that you are a user who is under the age of 13, we will unfortunately have to close your account. We don’t want to discourage you from learning to code, but those are the rules. Please see our Terms of Service for information about account termination.
</p>
<p><strong>International Users</strong></p>
<p>All the information you provide may be transferred or accessed by entities around the world as described in this Privacy Policy. Personal information, relating to Cryptvault services, regarding individuals who reside in a member state of the United States and Canada is controlled by Cryptvault head-office in England/Wales. Cryptvault, as a global company, has a number of legal entities in different jurisdictions which are responsible for the personal information which they collect and which is processed on their behalf by Cryptvault LTD. Cryptvault abides by the Asia-Pacific Economic Cooperation (APEC) Cross Border Privacy Rules System. The APEC CBPR system provides a framework for organizations to ensure protection of personal information transferred among participating APEC economies.
</p>
<p><strong>How we share the information we collect</strong></p>
<p>We do not share, sell, rent, or trade User Personal Information with third parties for their commercial purposes. We do not disclose User Personal Information outside Cryptvault except in the situations listed in this section or in the section below on Compelled Disclosure. We do share certain aggregated, non-personally identifying information with others about how our users, collectively, use Cryptvault or how our users respond to our other offerings, such as our conferences or events. For example, we may compile statistics on the usage of open source licenses across Cryptvault. However, we do not sell this information to advertisers or marketers.</p>

<p>We do not host advertising on Cryptvault. We may occasionally embed content from third party sites, such as YouTube, and that content may include ads. While we try to minimize the amount of ads our embedded content contains, we can’t always control what third parties show. We may share User Personal Information with your permission, so we can perform services you have requested. We may share User Personal Information with a limited number of third-party vendors who process it on our behalf to provide or improve our service, and who have agreed to privacy restrictions similar to our own Privacy Statement. Our vendors perform services such as payment processing, customer support ticketing, network data transmission, and other similar services. When we transfer your data to our vendors under Privacy Shield, we remain responsible for it. We may share User Personal Information if we are involved in a merger, sale, or acquisition. If any such change of ownership happens, we will ensure that it is under terms that preserve the confidentiality of User Personal Information, and we will notify you on our website or by email before any transfer of your User Personal Information. The organization receiving any User Personal Information will have to honor any promises we have made in our Privacy Statement or in our Terms of Service.</p>

<p><strong>Public Information on Cryptvault</strong></p>
<p>Much of Cryptvault is public-facing. If your content is public-facing, third parties may access and use it in compliance with our Terms of Service. We do not sell that content; it is yours. However, we do allow third parties, such as research organizations or archives, to compile public-facing Cryptvault information. Your Personal Information, associated with your content, may be gathered by third parties in these compilations of Cryptvault data. If you do not want your Personal Information to appear in third parties’ compilations of Cryptvault data, please do not make your Personal Information publicly available and be sure to configure your email address to be private in your user profile. If you would like to compile Cryptvault data, you may only use any public-facing Personal Information you gather for the purpose for which our user has authorized it. For example, where a Cryptvault user has made an email address public-facing for the purpose of identification and attribution, do not use that email address for commercial advertising. We expect you to reasonably secure any Personal Information you have gathered from Cryptvault, and to respond promptly to complaints, removal requests, and “do not contact” requests from Cryptvault or Cryptvault users. Similarly, projects on Cryptvault may include publicly available Personal Information collected as part of the collaborative process. In the event that a Cryptvault project contains publicly available Personal Information that does not belong to Cryptvault users, we will only use that Personal Information for the limited purpose for which it was collected, and we will secure that Personal Information as we would secure any User Personal Information. If you have a complaint about any Personal Information on Cryptvault, please see our section on resolving complaints. Our use of cookies and tracking</p>

<p><strong>Cookies</strong></p>
<p>Cryptvault uses cookies to make interactions with our service easy and meaningful. We use cookies (and similar technologies, like HTML5 localStorage) to keep you logged in, remember your preferences, and provide information for future development of Cryptvault. A cookie is a small piece of text that our web server stores on your computer or mobile device, which your browser sends to us when you return to our site. Cookies do not necessarily identify you if you are merely visiting Cryptvault; however, a cookie may store a unique identifier for each logged in user. The cookies Cryptvault sets are essential for the operation of the website, or are used for performance or functionality. By using our website, you agree that we can place these types of cookies on your computer or device. If you disable your browser or device’s ability to accept cookies, you will not be able to log in or use Cryptvaults services.
</p>
<p><strong>Google Analytics</strong></p>
<p>We use Google Analytics as a third party tracking service, but we don’t use it to track you individually or collect your User Personal Information. We use Google Analytics to collect information about how our website performs and how our users, in general, navigate through and use Cryptvault. This helps us evaluate our users’ use of Cryptvault; compile statistical reports on activity; and improve our content and website performance. Google Analytics gathers certain simple, non-personally identifying information over time, such as your IP address, browser type, internet service provider, referring and exit pages, time stamp, and similar data about your use of Cryptvault. We do not link this information to any of your personal information such as your user name. Cryptvault will not, nor will we allow any third party to, use the Google Analytics tool to track our users individually; collect any User Personal Information other than IP address; or correlate your IP address with your identity. Google provides further information about its own privacy practices and offers a browser add-on to opt out of Google Analytics tracking. Certain pages on our site may set other third party cookies. For example, we may embed content, such as videos, from another site that sets a cookie. While we try to minimize these third party cookies, we can’t always control what cookies this third party content sets.</p> 
<p><strong>Tracking</strong></p>

<p>“Do Not Track” is a privacy preference you can set in your browser if you do not want online services to collect and share certain kinds of information about your online activity from third party tracking services. We do not track your online browsing activity on other online services over time and we do not permit third-party services to track your activity on our site beyond our basic Google Analytics tracking, which you may opt out of here. Because we do not share this kind of data with third party services or permit this kind of third party data collection on Cryptvault for any of our users, and we do not track our users on third-party websites ourselves, we do not need to respond differently to an individual browser’s Do Not Track setting. If you are interested in turning on your browser’s privacy and Do Not Track settings, the Do Not Track website has browser-specific instructions. Please see our section on email communication to learn about our use of pixel tags in marketing emails. How Cryptvault secures your information
</p>
<p>Cryptvault takes all measures reasonably necessary to protect User Personal Information from unauthorized access, alteration, or destruction; maintain data accuracy; and help ensure the appropriate use of User Personal Information. We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission, or method of electronic storage, is 100% secure. Therefore, we cannot guarantee its absolute security. For more information, see our security disclosures. Cryptvault’s global privacy practices Information that we collect will be stored and processed in the United Kingdom in accordance with this Privacy Statement. However, we understand that we have users from different countries and regions with different privacy expectations, and we try to meet those needs. We provide the same standard of privacy protection to all our users around the world, regardless of their country of origin or location, and we are proud of the levels of notice, choice, accountability, security, data integrity, access, and recourse we provide. We have appointed a Privacy Counsel and we work hard to comply with the applicable data privacy laws wherever we do business. Additionally, we require that if our vendors or affiliates have access to User Personal Information, they must comply with our privacy policies and with applicable data privacy laws, including signing data transfer agreements such as Standard Contractual Clause agreements. In particular: * Cryptvault provides clear methods of unambiguous, informed consent at the time of data collection, when we do collect your personal data.</p>
<p>* We collect only the minimum amount of personal data necessary, unless you choose to provide more. We encourage you to only give us the amount of data you are comfortable sharing.</p>
<p>* We offer you simple methods of accessing, correcting, or deleting the data we have collected.</p>
<p>* We provide our users notice, choice, accountability, security, and access, and we limit the purpose for processing. We also provide our users a method of recourse and enforcement. These are the Privacy Shield Principles, but they are also just good practices.</p>
<p>* Cryptvault adheres to the Privacy Shield Framework. In addition to providing our users methods of unambiguous, informed consent and control over their data, we participate in and comply with the Privacy Shield framework, and we are committed to subject any Personal Information we receive from the UN and EEA to the Privacy Shield Principles. In addition, we continue to participate in the Safe Harbor Framework for Swiss data transfers to the UK.</p>
<p><strong>Resolving Complaints</strong></p>

<p>If you have concerns about the way Cryptvault is handling your User Personal Information, please let us know immediately. We want to help. You may contact us by filling out the Privacy contact form. You may also email us directly at <a href="mailto:hello@mycryptvault.com">hello@mycryptvault.com</a> the subject line “Privacy Shield Concerns.” We will respond within 45 days at the latest. Dispute Resolution Process</p>

<p>In the unlikely event that a dispute arises between you and Cryptvault regarding our handling of your User Personal Information, we will do our best to resolve it. If we cannot, we have selected JAMS, an independent dispute resolution provider, to handle unresolved Privacy Shield complaints. Independent Arbitration</p>

<p>Under certain limited circumstances, European Union individuals may invoke binding Privacy Shield arbitration as a last resort if all other forms of dispute resolution have been unsuccessful. To learn more about this method of resolution and its availability to you, please read more about Privacy Shield. We are subject to the jurisdiction of the Federal Trade Commission.</p>

<p><strong>How we respond to compelled disclosure</strong></p>
<p>Cryptvault may disclose personally-identifying information or other information we collect about you to law enforcement in response to a valid subpoena, court order, warrant, or similar government order, or when we believe in good faith that disclosure is reasonably necessary to protect our property or rights, or those of third parties or the public at large. In complying with court orders and similar legal processes, Cryptvault strives for transparency. When permitted, we will make a reasonable effort to notify users of any disclosure of their information, unless we are prohibited by law or court order from doing so, or in rare, exigent circumstances. For more information, see our Guidelines for Legal Requests of User Data.</p>

<p>How you can access and control the information we collect If you’re already a Cryptvault user, you may access, update, alter, or delete your basic user profile information by editing your user profile or contacting Cryptvault Support.</p>

<p><strong>Data Retention and Deletion</strong></p>
<p>Cryptvault will retain User Personal Information for as long as your account is active or as needed to provide you services.
</p>
<p>We may retain certain User Personal Information indefinitely, unless you delete it or request its deletion. For example, we don’t automatically delete inactive user accounts, so unless you choose to delete your account, we will retain your account information indefinitely. If you would like to cancel your account or delete your User Personal Information, you may do so in your user profile. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements, but barring legal requirements, we will delete your full profile (within reason) within 30 days.
</p>
<p><strong>How we communicate with you</strong></p>
<p>We will use your email address to communicate with you, if you’ve said that’s okay, and only for the reasons you’ve said that’s okay. You have a lot of control over how your email address is used and shared on and through Cryptvault. You may manage your communication preferences in your user profile. If you would like your email to remain private, even when you’re commenting on public repositories, you can create a private email address in your user profile. You can also update your local BiG configuration to use your private email address. This will not change how we contact you, but it will affect how others see you. Depending on your email settings, Cryptvault may occasionally send notification emails about changes in a repository you’re watching, new features, requests for feedback, important policy changes, or offer customer support. We also send marketing emails, but only with your consent. There’s an unsubscribe link located at the bottom of each of the emails we send you. Our emails might contain a pixel tag, which is a small, clear image that can tell us whether or not you have opened an email and what your IP address is. We use this pixel tag to make our email more effective for you and to make sure we’re not sending you unwanted email. If you prefer not to receive pixel tags, please opt out of marketing emails. Changes to our Privacy Statement</p>

<p>Although most changes are likely to be minor, Cryptvault may change our Privacy Statement from time to time. We will provide notification to Users of material changes to this Privacy Statement through our Website at least 30 days prior to the change taking effect by posting a notice on our home page or sending email to the email address specified in your Cryptvault primary account. For changes to this Privacy Statement that do not affect your rights, we encourage visitors to check this page frequently.</p>
<p><strong> License</strong></p>

<p>This Privacy Statement is licensed under this Creative Commons Zero license. For details, see our site-policy repository.</p>
            </div>
        </div>
        <br>
        <br>
        <br>
        <hr>
      </section>
    </main>






@stop